# Generated by Django 5.2.1 on 2026-03-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Category',
            new_name='category',
        ),
    ]
