# Generated by Django 5.2.1 on 2026-04-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwprd',
            new_name='password',
        ),
    ]
