# Generated by Django 5.2.1 on 2026-07-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
